# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
# exit: false # could be expressed as "no-exit: true"
extension:
  - 'js'
recursive: false
# reporter: 'spec'
# reporter-option:
#   - 'foo=bar'
#   - 'baz=quux'
require: 'ts-node/register'
retries: 1
slow: 75
sort: false
# spec: 'tasks/**/tests/**/*.spec.js' # the positional arguments!
timeout: false # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
# ui: 'bdd'
# v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
# watch: false
watch-files:
  - 'tasks/**/*.js'
  - 'tasks/**/tests/**/*.js'
watch-ignore:
  - '**/node_modules'
